"""add_plaid_item_model

Revision ID: 1f6cdd82dabd
Revises: c93da1011d16
Create Date: 2025-11-24 23:24:15.576208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f6cdd82dabd'
down_revision = 'c93da1011d16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plaid_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plaid_item_id', sa.String(length=128), nullable=False),
    sa.Column('plaid_access_token', sa.String(length=512), nullable=False),
    sa.Column('institution_name', sa.String(length=255), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plaid_item_id')
    )
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plaid_item_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_account_plaid_item_id', 'plaid_item', ['plaid_item_id'], ['id'])

    # Skip if constraints already exist (for partial migration recovery)
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_constraints = {c['name'] for c in inspector.get_unique_constraints('transaction')}
    existing_fks = {fk['name'] for fk in inspector.get_foreign_keys('transaction')}
    
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        if 'uq_transaction_plaid_tx_id' not in existing_constraints:
            batch_op.create_unique_constraint('uq_transaction_plaid_tx_id', ['plaid_tx_id'])
        if 'fk_transaction_account_id' not in existing_fks:
            batch_op.create_foreign_key('fk_transaction_account_id', 'account', ['account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transaction_account_id', type_='foreignkey')
        batch_op.drop_constraint('uq_transaction_plaid_tx_id', type_='unique')

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_constraint('fk_account_plaid_item_id', type_='foreignkey')
        batch_op.drop_column('plaid_item_id')

    op.drop_table('plaid_item')
    # ### end Alembic commands ###
