"""Add Plaid support

Revision ID: c93da1011d16
Revises: fa3f1401bb90
Create Date: 2025-11-24 20:16:10.895614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c93da1011d16'
down_revision = 'fa3f1401bb90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plaid_account_id', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('mask', sa.String(length=10), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('subtype', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plaid_account_id')
    )
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('plaid_tx_id', sa.String(length=128), nullable=True))
        batch_op.create_unique_constraint('uq_transaction_plaid_tx_id', ['plaid_tx_id'])
        batch_op.create_foreign_key('fk_transaction_account_id', 'account', ['account_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plaid_access_token', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('plaid_access_token')

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transaction_account_id', type_='foreignkey')
        batch_op.drop_constraint('uq_transaction_plaid_tx_id', type_='unique')
        batch_op.drop_column('plaid_tx_id')
        batch_op.drop_column('account_id')

    op.drop_table('account')
    # ### end Alembic commands ###
